import assert from 'node:assert/strict';
import fs from 'node:fs';
import { PDFDocument } from 'pdf-lib';
import * as mupdf from 'mupdf';
import { inspectDocument, writeAnnotations } from '../../src/engine/mupdf-engine.mjs';
const source = await PDFDocument.create(); source.addPage([420, 600]);
const bytes = await source.save();
const ink = { id:'ink-roundtrip', page:1, kind:'ink', rect:[38,98,205,155], inkPaths:[[40,100,80,130,120,115,200,150]], strokeWidth:3, color:'#2455b5', text:'', created:Date.now() };
const saved = writeAnnotations(bytes, [ink]);
const read = inspectDocument(saved);
assert.equal(read.annotations.length, 1); assert.equal(read.annotations[0].kind, 'ink');
assert.deepEqual(read.annotations[0].inkPaths, ink.inkPaths); assert.equal(read.annotations[0].strokeWidth, 3);
assert.equal(read.annotations[0].color, ink.color);
const document = new mupdf.PDFDocument(saved), page = document.loadPage(0);
assert.equal(page.getAnnotations()[0].getType(),'Ink');
assert(page.getAnnotations()[0].getObject().get('AP','N').isIndirect());
page.destroy(); document.destroy();
const removed = inspectDocument(writeAnnotations(saved, [])); assert.equal(removed.annotations.length, 0);
assert.throws(() => writeAnnotations(bytes, [{...ink, inkPaths:[[NaN,0,1,2]]}]));
assert.throws(() => writeAnnotations(bytes, [{...ink, strokeWidth:0}]));
const rotated = await PDFDocument.load(bytes); const {degrees} = await import('pdf-lib'); rotated.getPage(0).setRotation(degrees(90));
assert.deepEqual(inspectDocument(writeAnnotations(await rotated.save(), [ink])).annotations[0].inkPaths, ink.inkPaths);
fs.mkdirSync('test-results/android',{recursive:true}); fs.writeFileSync('test-results/android/ink.pdf',saved);
console.log('PASS: Ink PDF subtype, appearance, color, width, coordinates, rotated page, deletion and invalid data');
