"""Build a source-grounded, standalone report of the delivered development base."""
from pathlib import Path
from collections import Counter
import argparse, json, html, shutil

parser=argparse.ArgumentParser()
parser.add_argument('--out', required=True, type=Path)
parser.add_argument('--designs', required=True, type=Path)
args=parser.parse_args()
root=Path(__file__).resolve().parent.parent
out=args.out; out.mkdir(parents=True,exist_ok=True)
esc=html.escape
browser=json.loads((root/'test-results/browser-results.json').read_text())
engine=json.loads((root/'test-results/engine-results.json').read_text())
interop=json.loads((root/'test-results/interoperability-results.json').read_text())
assert not any(r['status']=='failed' for r in browser['results']+engine['results'])
assert not browser.get('uncaughtErrors')
counts=Counter(r['status'] for r in browser['results'])
for folder in ['evidence','designs']:(out/folder).mkdir(exist_ok=True)
for p in (root/'test-results').iterdir():
    if p.is_file():shutil.copy2(p,out/'evidence'/p.name)
shutil.copy2(root/'.fixtures/manifest.json',out/'evidence/corpus-manifest.json')
shutil.copy2(root/'dependency-licenses.json',out/'dependency-licenses.json')

modules=[
 ('Lectura y navegación','Probado en navegador; escritorio compilado','Lectura, texto, miniaturas, índice, búsqueda, zoom, marcadores y giro de vista.','Lectura PDF.js conservada. Impresión nativa deshabilitada. No se guardan rotaciones. Faltan pruebas Windows, memoria en archivos pesados, accesibilidad, capas y enlaces complejos.'),
 ('Anotaciones','Implementado y probado: notas/resaltados','Text y Highlight estándar, Unicode, importación, edición del texto de nota, borrado, deshacer/rehacer y exportación.','Selección de área rectangular; no resaltado por palabras. Otros tipos y comentarios bloqueados se conservan sin ofrecer edición. MuPDF/Poppler/pypdf comprobaron salidas; apertura manual en lectores Windows pendiente.'),
 ('Edición de texto e imágenes','Borrador; no implementado','Diseño de selección de objetos, sustitución y revisión.','PDF no equivale a un documento de párrafos. Fuentes parciales, ligaduras, texto convertido a trazos y clipping requieren prototipos. Dibujar encima no se aceptará como edición del contenido.'),
 ('OCR','Borrador; no implementado','El escaneo de prueba se muestra correctamente.','No se reconoce texto ni se puede buscar en ese escaneo. Se propone Tesseract/Leptonica con idiomas, revisión y capa textual; habrá errores de reconocimiento y límites para manuscritos/maquetación.'),
 ('Formularios','Lectura estática y conservación probadas','W9 visible; campos/valores originales conservados después de anotar.','Cero controles interactivos en el visor. Completar, crear y generar apariencias AcroForm pendientes. XFA dinámico y scripts necesitan evaluación separada.'),
 ('Firmas digitales','Detección conservadora probada; firma no existe','Una estructura de firma detectada bloquea cambios.','Las pruebas usan estructuras sintéticas, incluidas con tipo de campo heredado. No verifican certificados, ByteRange, confianza, revocación ni sello de tiempo. PAdES/CNG/PKCS#11 requieren otro componente e integración.'),
 ('Organización de páginas','Borrador; no implementado','Miniaturas y navegación disponibles.','No se puede guardar reordenado, dividir, combinar, insertar, extraer o eliminar páginas. Se propone qpdf/motor PDF; debe preservar destinos, enlaces y campos y considerar firmas.'),
 ('Conversión y compresión','Borrador; no implementado','Diseños de calidad, revisión y exportación.','PDF→Office exige reconstrucción y no promete fidelidad general. LibreOffice opcional sirve principalmente para Office→PDF. PDF/A requiere validador. Compresión con pérdida necesita advertencia y comparación real.'),
 ('Comparación de documentos','Borrador; no implementado','Diseño de alineación y revisión de cambios.','Hace falta combinar texto/objetos con comparación visual. OCR, reflujo y cambios de fuentes producen falsos positivos; hay que ensayar cambios sembrados y documentos idénticos.'),
 ('Protección y censura permanente','Lectura cifrada/exportación parcial probadas; censura ausente','El derivado W9 AES-256 abre con contraseña y conserva cifrado al guardar notas; se respetan permisos de anotación.','Crear/cambiar contraseñas en la interfaz y aplicar censura pendientes. No hay herramienta de tapado presentada como eliminación. La censura debe quitar texto, píxeles y contenedores, y pasar extracción/objetos/OCR independientes.'),
]
dependencies=[
 ('React/React DOM 19.3.0 · Lucide 0.468.0 · DM Sans','MIT · ISC · OFL 1.1','Interfaz existente y recursos visuales. Sin canon de licencia.'),
 ('PDF.js 5.7.284','Apache-2.0 y avisos de recursos','Render y navegación. No es motor de edición ni censura.'),
 ('MuPDF.js 1.28.1','AGPL-3.0-or-later','Motor WASM nuevo, sin modificaciones. La fuente de Folio y la fuente completa upstream acompañan la entrega. Una versión cerrada requeriría licencia comercial de Artifex o cambiar de motor.'),
 ('Tauri 2 · Rust · plugins de diálogos e instancia única','MIT/Apache-2.0 y licencias transitivas','Contenedor, archivos, sesiones y eventos. WebView2 es un runtime separado sujeto a las condiciones de Microsoft.'),
 ('qpdf · Tesseract/Leptonica · pyHanko · LibreOffice','Apache-2.0 · Apache/BSD · MIT · MPL y otras','Componentes propuestos; no incorporados a esta versión. Firmas del sistema/token y móvil requieren adaptadores.'),
 ('Firma de código · certificados PDF · TSA','Según proveedor','No comprados ni usados en la entrega. Pueden tener costo; son servicios distintos. El instalador actual no está firmado.'),
]
phases=[
 ('0 · Auditoría y diseño','Hecho; conservar evaluación histórica y copia del visor.','Estado por módulo, licencias, diez borradores y corpus con origen/hashes.'),
 ('1 · Base Windows','Compilada y empaquetada; aceptación nativa pendiente.','Instalar/desinstalar, abrir desde Explorer, diálogos, permisos, disco lleno, cierre, interrupción de guardado y recuperación. Medir RAM/latencia en Windows 10/11 y un archivo pesado.'),
 ('2 · Anotaciones y páginas','Notas/resaltados implementados; ampliar y organizar páginas.','Reabrir comentarios editables en Acrobat y otro lector Windows, selección textual y más tipos. Mover/combinar conserva contenido, destinos y formularios.'),
 ('3 · Edición del contenido','Pendiente de prototipo técnico del motor.','Texto retirado ausente en extracción; imágenes y regiones ajenas conservadas. Probar fuentes parciales/ligaduras/reflujo y bloquear casos no soportados.'),
 ('4 · OCR y AcroForm','Pendiente.','Medir errores frente a texto de referencia, conservar imagen original y revisar palabras dudosas. Campos, valores y apariencia coinciden en lectores independientes.'),
 ('5 · Comparación, conversión y compresión','Pendiente.','Corpus de cambios sembrados; documento idéntico sin cambios sustantivos. Medir tamaño/fidelidad y verificar PDF/A antes de ofrecerlo.'),
 ('6 · Firmas y protección','Pendiente; detección de estructuras ya evita cambios.','Certificados válidos/desconocidos/expirados, documento manipulado, firmas múltiples y DocMDP; validación independiente. Probar almacén Windows/tokens realmente.'),
 ('7 · Censura permanente','Pendiente; no se habilita antes de verificar eliminación.','Secretos en texto visible/invisible, imágenes, XObjects, capas, ActualText, XMP, campos, adjuntos y revisiones. Deben faltar en dos extractores, streams, imágenes y OCR; regiones ajenas conservadas.'),
 ('8 · Otras plataformas y mejoras','Pendiente tras la base de escritorio.','Repetir el mismo corpus por plataforma. Adaptar archivos, llaveros y firma; servicios Python/LibreOffice no se trasladan automáticamente a móvil/web.'),
]
drafts=[
 ('01-lectura-anotaciones.png','Lectura y anotaciones','Abrir → buscar/navegar → resaltar/comentar → guardar. Lectura y subconjunto de comentarios ya existen; la pantalla es un borrador.'),
 ('02-edicion-ocr.png','Edición y OCR','Seleccionar objeto → cambiar → revisar. Elegir idioma → reconocer → corregir → generar capa de texto. Ambas herramientas pendientes.'),
 ('03-formularios-firmas.png','Formularios y firmas','Detectar/crear campos → completar → guardar. Elegir certificado → verificar → firmar. Completar formularios y firmar pendientes.'),
 ('04-paginas-conversion.png','Páginas y conversión','Seleccionar/reordenar → revisar → guardar copia. Elegir formato/calidad → previsualizar → procesar. Pendientes.'),
 ('05-comparacion-proteccion.png','Comparación y protección','Elegir versiones → alinear → revisar. Marcar datos → aplicar eliminación → limpiar → verificar. Pendientes.'),
]
for name,_,_ in drafts:shutil.copy2(args.designs/name,out/'designs'/name)
shutil.copy2(args.designs/'12-iconos-elegidos-pliegue.png',out/'designs/12-iconos-elegidos-pliegue.png')
shutil.copy2(root/'public/folio.svg',out/'designs/folio.svg')
shutil.copy2(root/'public/folio-file.svg',out/'designs/folio-file.svg')

css='''
:root{--ink:#252b27;--muted:#606b60;--coral:#cf4e39;--paper:#f8f7f3;--line:#deded7}
*{box-sizing:border-box}body{background:var(--paper);color:var(--ink);font:16px/1.6 system-ui,sans-serif;margin:0}
main{max-width:1180px;margin:auto;padding:42px 32px 70px}h1{font-size:44px;line-height:1.15;margin:12px 0 18px}h2{font-size:29px;margin:38px 0 16px}h3{margin:24px 0 8px}a{color:#9f3929}p{margin:12px 0}small,.muted{color:var(--muted)}
.eyebrow{color:var(--coral);letter-spacing:2px;font-size:12px;font-weight:700}.notice{padding:20px;border:1px solid #dab4a6;border-left:5px solid var(--coral);border-radius:10px;background:#fff3ec}
.stats,.flow{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:24px 0}.stat,.node{background:white;border:1px solid var(--line);padding:16px;border-radius:10px}.stat b{display:block;font-size:30px}.node b{display:block}.node small{display:block;margin-top:8px}
nav{display:flex;flex-wrap:wrap;gap:16px;margin:24px 0}table{width:100%;border-collapse:collapse;font-size:14px;background:white;margin:16px 0}th,td{padding:12px;text-align:left;border:1px solid var(--line);vertical-align:top}th{background:#eaece5}td:first-child{font-weight:650}figure{margin:24px 0;background:white;padding:14px;border:1px solid var(--line);border-radius:10px}figure img{max-width:100%;height:auto;display:block;margin:auto}figcaption{font-size:13px;margin-top:10px;color:var(--muted)}.screen img{max-height:660px}.draft img{max-height:850px}.icons img{max-height:380px}code{background:#eaece5;padding:2px 5px;border-radius:4px}li{margin:6px 0}details{border:1px solid var(--line);background:white;border-radius:8px;padding:12px;margin:12px 0}summary{cursor:pointer;font-weight:650}.ok{color:#316449}.partial{color:#a26120}
@media(max-width:800px){main{padding:24px 16px}h1{font-size:34px}.stats,.flow{grid-template-columns:repeat(2,1fr)}table{font-size:12px}th,td{padding:8px}}
@page{size:A4;margin:15mm}@media print{body{background:white;font-size:10pt}main{padding:0;max-width:none}h1{font-size:30pt}h2{font-size:20pt}nav,.web-only{display:none}.stats{gap:6px}.stat{padding:10px}.stat b{font-size:20pt}.flow{grid-template-columns:repeat(2,1fr)}table{font-size:8.5pt}th,td{padding:6px}tr{break-inside:avoid}figure{break-inside:avoid;padding:8px}.screen img{max-height:170mm}.draft{break-before:page}.draft img{max-height:210mm}.icons img{max-height:85mm}h2,h3{break-after:avoid}a{color:inherit;text-decoration:none}details{break-inside:avoid}}
'''
parts=['<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Folio 0.2.0 · Avance comprobado</title><style>'+css+'</style><main><span class="eyebrow">FOLIO · WINDOWS 10/11 X64 · 03 OCT 2026</span><h1>Una base que ya guarda<br>comentarios PDF reales.</h1><p>Entrega de desarrollo 0.2.0. Se conserva la lectura útil del visor y se reemplaza la exportación de gráficos por comentarios estándar. El contenedor Tauri, el ejecutable Windows y el instalador NSIS están generados.</p><div class="notice"><b>Instalador experimental; aceptación Windows pendiente.</b><br>La compilación y el empaquetado se comprobaron desde Linux. La instalación, los diálogos nativos, el inicio desde Explorer y las asociaciones todavía no se ejecutaron en Windows. La suite completa continúa en desarrollo.</div>']
parts.append(f'<div class="stats"><div class="stat"><b>{counts["passed"]}</b>recorridos de interfaz aprobados</div><div class="stat"><b>{counts["partial"]}</b>recorridos con límites explícitos</div><div class="stat"><b>{len(engine["results"])}</b>pruebas de motor aprobadas</div><div class="stat"><b>4</b>pruebas de archivos Rust aprobadas</div></div>')
parts.append('<p class="muted">Plataforma de prueba: Linux/Chromium, Node/WASM y herramientas independientes. Cero pruebas del contenedor ejecutadas en Windows. Las 3 parciales corresponden a preparación de impresión web, escaneo sin OCR y formulario sin controles.</p><nav><a href="#cambios">Cambios</a><a href="#arquitectura">Arquitectura</a><a href="#modulos">Módulos</a><a href="#pruebas">Pruebas</a><a href="#visuales">Visuales</a><a href="#etapas">Etapas</a><a href="#entrega">Entrega</a></nav>')
parts.append('<section id="cambios"><h2>Qué cambió realmente</h2><table><tr><th>Área</th><th>Versión auditada</th><th>0.2.0 comprobado</th></tr><tr><td>Comentarios</td><td>Gráficos dibujados y notas como páginas adicionales; cero comentarios estándar.</td><td>Text/Highlight estándar con apariencias. Reimportar, editar nota, borrar y guardar sin duplicar ni agregar páginas.</td></tr><tr><td>Unicode</td><td>Caracteres 漢字 🙂 se sustituían por signos de interrogación.</td><td>Contenido Unicode conservado y leído con pypdf; ubicación ensayada con recorte y cuatro rotaciones.</td></tr><tr><td>Archivo cifrado</td><td>Lectura correcta; fallaba exportar anotaciones.</td><td>Derivado W9 AES-256 exportado y reabierto con la misma contraseña.</td></tr><tr><td>Escritorio</td><td>Visor web; sin instalador.</td><td>Backend Tauri/Rust compilado para MSVC e instalador NSIS generado. Uso nativo pendiente de aceptación.</td></tr><tr><td>Iconos</td><td>Dirección visual elegida.</td><td>Pliegue integrado en SVG y recursos ICO multiresolución para programa y archivo PDF. Asociación/icono en Explorer pendientes de prueba.</td></tr></table><p>La copia congelada del visor y la evaluación histórica se mantienen separadas de esta implementación. El reporte anterior sigue documentando el estado previo.</p></section>')
parts.append('<section id="arquitectura"><h2>Arquitectura instalada y base reutilizable</h2><div class="flow"><div class="node"><b>React + PDF.js</b><small>Interfaz, render, texto, navegación y búsqueda conservados.</small></div><div class="node"><b>MuPDF.js / WASM</b><small>Inspeccionar/importar/guardar comentarios en worker cancelable por operación.</small></div><div class="node"><b>Adaptador de plataforma</b><small>Descarga web o IPC binario/diálogos Tauri; los bytes originales se conservan.</small></div><div class="node"><b>Rust / Tauri</b><small>Archivos, guardado de copia, sesiones JSON y eventos de apertura.</small></div></div><p>Se eligió MuPDF en WASM para compartir el motor entre la aplicación de escritorio y el navegador. El enlace C nativo previsto en el primer diseño no se incorporó en esta fase. Las sesiones usan JSON atómico; SQLite queda pendiente. El render todavía depende de PDF.js en la interfaz y la separación completa del dominio seguirá ampliándose.</p><p>Entrada nativa máxima: <b>100 MiB</b>; salida: <b>128 MiB</b>. Se recibe el archivo completo y aún no hay lectura por bloques ni límite duro de memoria WASM. Cada trabajo tiene cancelación y plazo de 90 segundos; se limita el tamaño de los canvas. Esto no acredita rendimiento de archivos de 100 MiB.</p><p>El guardado nativo prepara una copia temporal y confirma su escritura. Rechaza el original y sus alias, y comprueba el destino después del diálogo. Las cuatro pruebas Rust verificaron esa lógica en Linux; quedan fallos de almacenamiento/interrupción y comportamiento Windows por ensayar. Las sesiones y notas locales no están cifradas. La contraseña se mantiene en RAM.</p><h3>Dependencias, licencias y posibles costos</h3><table><tr><th>Componente</th><th>Licencia</th><th>Uso / costo</th></tr>')
for row in dependencies:parts.append('<tr>'+''.join('<td>'+esc(c)+'</td>' for c in row)+'</tr>')
parts.append('</table><p>Los avisos completos y las versiones exactas están en THIRD-PARTY-NOTICES.txt y <a href="dependency-licenses.json">dependency-licenses.json</a>. El instalador incluye LICENSE.txt, avisos e instrucciones de fuente. Necesita Internet para descargar WebView2 si el equipo no lo tiene; después el lector trabaja localmente. No hay publicación del sitio ni actualización automática configurada.</p></section>')
parts.append('<section id="modulos"><h2>Estado actual de los diez módulos</h2><table><tr><th>Módulo / estado</th><th>Disponible o propuesto</th><th>Límites reales</th></tr>')
for name,state,available,limits in modules:parts.append('<tr><td>'+esc(name)+'<br><small>'+esc(state)+'</small></td><td>'+esc(available)+'</td><td>'+esc(limits)+'</td></tr>')
parts.append('</table></section><section id="pruebas"><h2>Resultados y alcance de las pruebas</h2><p>Corpus real: artículo TraceMonkey (14 páginas), manual Emacs (804 páginas / 3,08 MB), escaneo público sin texto y formulario IRS W9 (6 páginas). Se usó además un derivado cifrado controlado del W9. Los archivos restringidos, las estructuras de firma y las cuatro rotaciones son casos de prueba construidos.</p><p>Los cinco PDF anotados se reabrieron con MuPDF y pypdf. Se compararon páginas, texto, hashes de imágenes, valores de campos y bytes decodificados de los streams de contenido originales. Poppler renderizó y extrajo texto de salidas no cifradas. Unicode, borrado de comentarios y conservación de recorte/rotación también se comprobaron.</p><p><b>Límite:</b> todavía falta abrir manualmente esas salidas en Acrobat/Foxit/PDF-XChange bajo Windows. No se ha probado edición del texto original ni eliminación permanente de secretos, porque esas herramientas no existen en el producto.</p><table><tr><th>Recorrido de interfaz</th><th>Resultado</th></tr>')
labels={
 'initial-sample-and-ui':'Carga inicial y lectura', 'real-text-navigation-search-zoom-rotation':'Texto, navegación, búsqueda, zoom y giro de vista', 'annotations-undo-redo-note-export':'Resaltado, nota, historia y exportación estándar', 'local-library-reopen':'Restauración de sesión web', 'original-download-byte-preservation':'Copia original idéntica byte a byte', 'print-preparation-only':'Preparación de impresión web; impresora pendiente', 'real-scanned-pdf-no-ocr':'Escaneo visible; OCR ausente', 'real-acroform-read-not-fill':'W9 estático; completar ausente', 'aes256-password-wrong-correct-encrypted-export':'AES-256 y exportación conservando contraseña', 'password-cancel-preserves-current-document':'Cancelar contraseña conserva documento previo', 'large-real-804-page-document':'Primera/última página del manual de 804 páginas', 'invalid-pdf-is-rejected-without-destroying-current-document':'PDF inválido rechazado; documento previo conservado', 'reopen-standard-edit-unicode-delete-and-save':'Reimportar, editar Unicode y borrar todos los comentarios', 'restricted-document-disables-annotation-tools':'Permisos restringidos bloquean herramientas', 'signature-detection-readonly-without-validity-claim':'Detectar estructura de firma sin afirmar validez', 'privacy-local-requests-no-external-upload':'Solicitudes locales; sin envío de documentos'}
labels.update({'invalid-file-preserves-current-pdf':'PDF inválido rechazado; documento previo conservado','reopen-standard-annotations-and-unicode':'Reimportar, editar Unicode y borrar todos los comentarios','restricted-pdf-disables-annotation-tools':'Permisos restringidos bloquean herramientas','signature-detection-is-read-only-without-validity-claim':'Detectar estructura de firma sin afirmar validez','privacy-transport-during-tests':'Solicitudes locales; sin envío de documentos'})
for r in browser['results']:parts.append('<tr><td>'+esc(labels.get(r['id'],r['id']))+'</td><td class="'+('ok' if r['status']=='passed' else 'partial')+'">'+('Aprobado' if r['status']=='passed' else 'Parcial')+'</td></tr>')
parts.append('</table><p class="web-only"><a href="evidence/browser-results.json">Interfaz: JSON</a> · <a href="evidence/engine-results.json">Motor: JSON</a> · <a href="evidence/interoperability-results.json">Interoperabilidad: JSON</a> · <a href="evidence/corpus-manifest.json">Corpus: origen y SHA-256</a></p><p>El generador de corpus acepta copias ya descargadas y verifica su hash. El manual GNU respondió HTTP 403/503 al intentar descargarlo de nuevo; se verificó la copia de la auditoría. No se actualizan hashes automáticamente ante cambios de edición. Las mediciones del manual corresponden a una sola ejecución Linux y no son un benchmark Windows.</p></section>')
parts.append('<section id="visuales"><h2>Capturas reales y borradores de diseño</h2><h3>Interfaz ejecutada en navegador</h3><p>Las siguientes capturas provienen de las pruebas de la versión actual. El contenedor Windows no se capturó porque todavía no se ejecutó allí.</p>')
for filename,label in [('actual-annotations.png','Notas y resaltados exportados como comentarios estándar'),('actual-large-last-page.png','Página 804 del documento real'),('actual-form-static.png','Formulario visible con campos no interactivos')]:parts.append('<figure class="screen"><a href="evidence/'+filename+'"><img src="evidence/'+filename+'" alt="'+esc(label)+'"></a><figcaption>CAPTURA REAL · '+esc(label)+'</figcaption></figure>')
parts.append('<h3>Iconos implementados · opción 04 «Pliegue»</h3><p>Programa: tile coral con pliegue marfil. Archivo: hoja PDF con la misma marca. Recursos SVG e ICO de varias resoluciones generados e incorporados al instalador; falta comprobar el registro y la visualización del icono de archivo en Explorer.</p><figure class="icons"><img src="designs/12-iconos-elegidos-pliegue.png" alt="Dirección visual elegida para iconos"><figcaption>REFERENCIA APROBADA · Los recursos implementados se encuentran en public/ y assets/pdf-file-icons/ dentro de la fuente.</figcaption></figure><h3>Borradores coherentes para los diez módulos</h3><div class="notice">Estos dibujos muestran flujos propuestos. Sus etiquetas internas se generaron durante la evaluación original; la tabla de estado de esta entrega indica qué subconjunto existe hoy. Un dibujo no acredita implementación.</div>')
for filename,title,flow in drafts:parts.append('<figure class="draft"><h3>BORRADOR · '+esc(title)+'</h3><a href="designs/'+filename+'"><img src="designs/'+filename+'" alt="Borrador '+esc(title)+'"></a><figcaption>'+esc(flow)+'</figcaption></figure>')
parts.append('</section><section id="etapas"><h2>Etapas y pruebas de aceptación</h2><table><tr><th>Etapa / estado</th><th>Condición de aceptación</th></tr>')
for title,state,gate in phases:parts.append('<tr><td>'+esc(title)+'<br><small>'+esc(state)+'</small></td><td>'+esc(gate)+'</td></tr>')
parts.append('</table><h3>Próximo cierre: Windows 10/11</h3><ol><li>Instalación/desinstalación por usuario, WebView2 presente/ausente, apertura desde Explorer e instancia única.</li><li>Diálogos de abrir/guardar, rutas Unicode, rechazo del original, cancelación y fallos reales de disco/permisos.</li><li>Persistencia de sesión al cerrar, fallo de guardado de sesión y corte del proceso durante escritura.</li><li>Comentarios reabiertos y editables en al menos dos lectores Windows; formulario y cifrado conservados.</li><li>Medición de rendimiento y memoria con archivos pesados; impresión nativa antes de habilitarla.</li></ol><p>La lista detallada está en docs/acceptance-windows.md de la fuente. Estas condiciones siguen pendientes; no se cierran con pruebas del navegador.</p></section>')
parts.append('<section id="entrega"><h2>Archivos entregables y trazabilidad</h2><ul><li><a href="Folio_0.2.0_x64-setup.exe">Folio_0.2.0_x64-setup.exe</a>: instalador de desarrollo x64, sin firma de código.</li><li><a href="folio-0.2.0-fuente.zip">folio-0.2.0-fuente.zip</a>: fuente de la aplicación, lockfiles, iconos, licencias y harness de pruebas.</li><li><a href="sources/mupdf-1.28.1-source.tar.gz">mupdf-1.28.1-source.tar.gz</a>: fuente oficial completa del motor y componentes upstream.</li><li><a href="folio-0.2.0-evidencias.zip">folio-0.2.0-evidencias.zip</a>: resultados, capturas y salidas PDF comprobadas.</li><li><a href="SHA256SUMS.txt">SHA256SUMS.txt</a>: integridad de los entregables.</li></ul><p>Las etapas siguientes se apoyarán en estas regresiones. Edición y censura requieren demostrar modificación/eliminación del contenido real antes de incorporarse a la interfaz.</p><p class="muted">Informe generado a partir de resultados registrados el '+esc(browser.get('date','03/10/2026'))+'. Esta entrega acredita el subconjunto indicado; la aplicación profesional completa sigue pendiente.</p></section></main></html>')
(out/'avance-folio-0.2.html').write_text(''.join(parts))
(out/'estado-0.2.json').write_text(json.dumps({'version':'0.2.0','platformPriority':'Windows 10/11 x64','windowsBinaryCompiled':True,'windowsInstallerGenerated':True,'windowsRuntimeTested':False,'browserCounts':dict(counts),'enginePassed':len(engine['results']),'rustCorePassedOnLinux':4,'modules':modules,'phases':phases},ensure_ascii=False,indent=2))
print('Informe y evidencia copiados a '+str(out))
